Document: syncthing
Title: Debian syncthing Manual
Author: <insert document author here>
Abstract: This manual describes what syncthing is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/syncthing/syncthing.sgml.gz

Format: postscript
Files: /usr/share/doc/syncthing/syncthing.ps.gz

Format: text
Files: /usr/share/doc/syncthing/syncthing.text.gz

Format: HTML
Index: /usr/share/doc/syncthing/html/index.html
Files: /usr/share/doc/syncthing/html/*.html
